       
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace : default
  labels:
    name: rails-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: rails-app
    spec:
      containers:
      - name: rails-app # name of our container
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        command: ["/bin/sh","-c"]
        args: ["rails cequel:keyspace:create; rails cequel:migrate; rails server -b 0.0.0.0"]
        ports:
        - containerPort: 3000 # expose the running contianer on port 3000
          name: rails-app
          protocol: TCP
