apiVersion: autoscaling/v2beta1                    #autoscaling apiversion type
kind: HorizontalPodAutoscaler                      #kind of the kubernetes object to be created
metadata:
  name: rails-app                                  #metadata to reference selectors of pod
  namespace: default                               #namespace to which it has to be provisioned
spec:
  scaleTargetRef:                                  #which onject to be referenced
    apiVersion: apps/v1         
    kind: Deployment
    name: rails-app
  minReplicas: 3                                   #minimum and maximum replicas
  maxReplicas: 6
  metrics:                                         #metrics to which the be monitored
  - type: Resource
    resource:
      name: cpu                                    #cpu metrics to be monitored
      targetAverageUtilization: 50                 #targeted utilization threshold
