apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2020-07-11T10:07:03Z","generation":3,"labels":{"name":"rails-app"},"name":"rails-app","namespace":"default","resourceVersion":"452669","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/rails-app","uid":"44a409c5-c35e-11ea-84a6-42010a800216"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":3,"revisionHistoryLimit":2147483647,"selector":{"matchLabels":{"name":"rails-app"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"rails-app"}},"spec":{"containers":[{"args":["rails cequel:keyspace:create; rails cequel:migrate; rails server -b 0.0.0.0"],"command":["/bin/sh","-c"],"image":"daneshrao/rubyonrails:latest","imagePullPolicy":"Always","name":"rails-app","ports":[{"containerPort":3000,"name":"rails-app","protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2020-07-12T03:58:38Z","lastUpdateTime":"2020-07-12T03:58:38Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2020-07-11T10:07:03Z"
  generation: 4
  labels:
    name: rails-app
  name: rails-app
  namespace: default
  resourceVersion: "506949"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/rails-app
  uid: 44a409c5-c35e-11ea-84a6-42010a800216
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: rails-app
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: rails-app
    spec:
      containers:
      - args:
        - rails cequel:keyspace:create; rails cequel:migrate; rails server -b 0.0.0.0
        command:
        - /bin/sh
        - -c
        image: daneshrao/rubyonrails:latest
        imagePullPolicy: Always
        name: rails-app
        ports:
        - containerPort: 3000
          name: rails-app
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-07-12T03:58:38Z"
    lastUpdateTime: "2020-07-12T03:58:38Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
