apiVersion: v1                          #apiversion
kind: Service                           #kind of kubernetes object
metadata:
  name: rails-app                       #label to be grouped for
spec:
  selector:
    name: rails-app
  ports:
    - port: 3000                        #port on the node to pod mapping
      targetPort: 3000
  type: LoadBalancer                    #type of the service to be attaced to the pods
